name: Send telegram message

on:
  schedule:
  - cron: "0/5 * * * 1-5"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Telegram
      run: |
        python A50alarm.py
