name: Send telegram message

on:
  schedule:
  - cron: "0 43/1 10 ? * MON-FRI *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Telegram
      env:
        telegram_tocken: ${{ secrets.telegram_tocken }}
        telegram_mc: ${{ secrets.telegram_mc }}
      run: |
        python A50alarm.py
